### ISSUE TITLE
option 'arg' needs a date

### ISSUE THREAD

**Issue by utkarsh2102** [ManageIQ/optimist#109]
Here are the logs of the failure:

```
Optimist::ParserTest#test_date_formatting = 0.00 s = E


Error:
Optimist::ParserTest#test_date_formatting:
Optimist::CommandlineError: option 'arg' needs a date
    /home/utkarsh/debian/updates/ruby-team/optimist/ruby-optimist/lib/optimist.rb:842:in `rescue in block (2 levels) in parse'
    /home/utkarsh/debian/updates/ruby-team/optimist/ruby-optimist/lib/optimist.rb:833:in `block (2 levels) in parse'
    /home/utkarsh/debian/updates/ruby-team/optimist/ruby-optimist/lib/optimist.rb:831:in `map'
    /home/utkarsh/debian/updates/ruby-team/optimist/ruby-optimist/lib/optimist.rb:831:in `block in parse'
    /home/utkarsh/debian/updates/ruby-team/optimist/ruby-optimist/lib/optimist.rb:830:in `map'
    /home/utkarsh/debian/updates/ruby-team/optimist/ruby-optimist/lib/optimist.rb:830:in `parse'
    /home/utkarsh/debian/updates/ruby-team/optimist/ruby-optimist/lib/optimist.rb:327:in `block in parse'
    /home/utkarsh/debian/updates/ruby-team/optimist/ruby-optimist/lib/optimist.rb:316:in `each'
    /home/utkarsh/debian/updates/ruby-team/optimist/ruby-optimist/lib/optimist.rb:316:in `parse'
    /home/utkarsh/debian/updates/ruby-team/optimist/ruby-optimist/test/optimist/parser_test.rb:512:in `test_date_formatting'
    /usr/lib/ruby/vendor_ruby/minitest/test.rb:98:in `block (3 levels) in run'
    /usr/lib/ruby/vendor_ruby/minitest/test.rb:195:in `capture_exceptions'
    /usr/lib/ruby/vendor_ruby/minitest/test.rb:95:in `block (2 levels) in run'
    /usr/lib/ruby/vendor_ruby/minitest.rb:270:in `time_it'
    /usr/lib/ruby/vendor_ruby/minitest/test.rb:94:in `block in run'
    /usr/lib/ruby/vendor_ruby/minitest.rb:365:in `on_signal'
    /usr/lib/ruby/vendor_ruby/minitest/test.rb:211:in `with_info_handler'
    /usr/lib/ruby/vendor_ruby/minitest/test.rb:93:in `run'
    /usr/lib/ruby/vendor_ruby/minitest.rb:1029:in `run_one_method'
    /usr/lib/ruby/vendor_ruby/minitest.rb:339:in `run_one_method'
    /usr/lib/ruby/vendor_ruby/minitest.rb:326:in `block (2 levels) in run'
    /usr/lib/ruby/vendor_ruby/minitest.rb:325:in `each'
    /usr/lib/ruby/vendor_ruby/minitest.rb:325:in `block in run'
    /usr/lib/ruby/vendor_ruby/minitest.rb:365:in `on_signal'
    /usr/lib/ruby/vendor_ruby/minitest.rb:352:in `with_info_handler'
    /usr/lib/ruby/vendor_ruby/minitest.rb:324:in `run'
    /usr/lib/ruby/vendor_ruby/minitest.rb:164:in `block in __run'
    /usr/lib/ruby/vendor_ruby/minitest.rb:164:in `map'
    /usr/lib/ruby/vendor_ruby/minitest.rb:164:in `__run'
    /usr/lib/ruby/vendor_ruby/minitest.rb:141:in `run'
    /usr/lib/ruby/vendor_ruby/minitest.rb:68:in `block in autorun'


bin/rails test home/utkarsh/debian/updates/ruby-team/optimist/ruby-optimist/test/optimist/parser_test.rb:508
```

**Comment by utkarsh2102** [comment]
Ah, this is not failing. I miss to use the chroni library. Closing :)
But shall open another bug related to this because this is so weird!
